Graph-Easy
==========

This module lets you create graphs (nodes/vertices connected by edges/arcs,
not pie charts!) and then lay them out on a flat surface.

Once laid out, the graph can be converted into various output formats like
ASCII art, HTML or SVG. You can also output the graph in graphviz format
and let dot/neato/circo etc. do the layout for you.

Graphs can be either generated by Perl code, parsed from a simple text format
that is human readable and maintainable, or parsed from Graphviz code.

For instance this input:

	[ Bonn ] -> [ Berlin ]
	[ Berlin ] -> [ Frankfurt ] { border: 1px dotted black; }
	[ Frankfurt ] -> [ Dresden ]
	[ Berlin ] ..> [ Potsdam ]
	[ Potsdam ] => [ Cottbus ]

would be rendered in ASCII as:

	+------+     +--------+      .............     +---------+
	| Bonn | --> | Berlin |  --> : Frankfurt : --> | Dresden |
	+------+     +--------+      .............     +---------+
	               :
	               :
	               v
	             +---------+     +---------+
	             | Potsdam | ==> | Cottbus |
	             +---------+     +---------+

The HTML or SVG output would look similiar except be more pretty :o)

Manual
======

The manual is contained in the extra package Graph::Easy::Manual, which
also contains a Pod2HTML converter, that can handle embedded graphs
in POD files.

You can also view the manual online at:

	http://bloodgate.com/perl/graph/manual/

Many more examples and documentation, especially on integrating this into
a Mediawiki installation, can be found at:

	http://bloodgate.com/perl/graph/

Have fun!

SVG Output
==========

You also might want to install Graph::Easy::As_svg from CPAN, it provides
you with the ability to generate SVG (Scalable Vector Graphics) files.

Installation
============

See INSTALL on how to install this module.

AUTHOR
======

Copyright (C) 2004 - 2008 by Tels http://bloodgate.com/

This library is free software; you can redistribute it and/or modify
it under the same terms of the GPL version 2.

This module was formerly known as Graph-Simple, but has been renamed
because it can also easily create non-simple graphs.

